<?php

return [
    [
        'name' => 'Afghanistan',
        'flag' => '🇦🇫',
        'code' => 'AF',
        'dial_code' => '+93',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'Åland Islands',
        'flag' => '🇦🇽',
        'code' => 'AX',
        'dial_code' => '+358',
        'phone_mask' => '### #######',
    ], [
        'name' => 'Albania',
        'flag' => '🇦🇱',
        'code' => 'AL',
        'dial_code' => '+355',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'Algeria',
        'flag' => '🇩🇿',
        'code' => 'DZ',
        'dial_code' => '+213',
        'phone_mask' => '#### ## ## ##',
    ], [
        'name' => 'American Samoa',
        'flag' => '🇦🇸',
        'code' => 'AS',
        'dial_code' => '+1684',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Andorra',
        'flag' => '🇦🇩',
        'code' => 'AD',
        'dial_code' => '+376',
        'phone_mask' => '### ###',
    ], [
        'name' => 'Angola',
        'flag' => '🇦🇴',
        'code' => 'AO',
        'dial_code' => '+244',
        'phone_mask' => '### ### ###',
    ], [
        'name' => 'Anguilla',
        'flag' => '🇦🇮',
        'code' => 'AI',
        'dial_code' => '+1264',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Antarctica',
        'flag' => '🇦🇶',
        'code' => 'AQ',
        'dial_code' => '+672',
        'phone_mask' => '',
    ], [
        'name' => 'Antigua and Barbuda',
        'flag' => '🇦🇬',
        'code' => 'AG',
        'dial_code' => '+1268',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Argentina',
        'flag' => '🇦🇷',
        'code' => 'AR',
        'dial_code' => '+54',
        'phone_mask' => '### ##-####-####',
    ], [
        'name' => 'Armenia',
        'flag' => '🇦🇲',
        'code' => 'AM',
        'dial_code' => '+374',
        'phone_mask' => '### ######',
    ], [
        'name' => 'Aruba',
        'flag' => '🇦🇼',
        'code' => 'AW',
        'dial_code' => '+297',
        'phone_mask' => '### ####',
    ], [
        'name' => 'Australia',
        'flag' => '🇦🇺',
        'code' => 'AU',
        'dial_code' => '+61',
        'phone_mask' => '#### ### ###',
    ], [
        'name' => 'Austria',
        'flag' => '🇦🇹',
        'code' => 'AT',
        'dial_code' => '+43',
        'phone_mask' => '#### ######',
    ], [
        'name' => 'Azerbaijan',
        'flag' => '🇦🇿',
        'code' => 'AZ',
        'dial_code' => '+994',
        'phone_mask' => '### ### ## ##',
    ], [
        'name' => 'Bahamas',
        'flag' => '🇧🇸',
        'code' => 'BS',
        'dial_code' => '+1242',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Bahrain',
        'flag' => '🇧🇭',
        'code' => 'BH',
        'dial_code' => '+973',
        'phone_mask' => '#### ####',
    ], [
        'name' => 'Bangladesh',
        'flag' => '🇧🇩',
        'code' => 'BD',
        'dial_code' => '+880',
        'phone_mask' => '#####-######',
    ], [
        'name' => 'Barbados',
        'flag' => '🇧🇧',
        'code' => 'BB',
        'dial_code' => '+1246',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Belarus',
        'flag' => '🇧🇾',
        'code' => 'BY',
        'dial_code' => '+375',
        'phone_mask' => '# ### ###-##-##',
    ], [
        'name' => 'Belgium',
        'flag' => '🇧🇪',
        'code' => 'BE',
        'dial_code' => '+32',
        'phone_mask' => '#### ## ## ##',
    ], [
        'name' => 'Belize',
        'flag' => '🇧🇿',
        'code' => 'BZ',
        'dial_code' => '+501',
        'phone_mask' => '###-####',
    ], [
        'name' => 'Benin',
        'flag' => '🇧🇯',
        'code' => 'BJ',
        'dial_code' => '+229',
        'phone_mask' => '## ## ## ##',
    ], [
        'name' => 'Bermuda',
        'flag' => '🇧🇲',
        'code' => 'BM',
        'dial_code' => '+1441',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Bhutan',
        'flag' => '🇧🇹',
        'code' => 'BT',
        'dial_code' => '+975',
        'phone_mask' => '## ## ## ##',
    ], [
        'name' => 'Bolivia, Plurinational State of bolivia',
        'flag' => '🇧🇴',
        'code' => 'BO',
        'dial_code' => '+591',
        'phone_mask' => '########',
    ], [
        'name' => 'Bosnia and Herzegovina',
        'flag' => '🇧🇦',
        'code' => 'BA',
        'dial_code' => '+387',
        'phone_mask' => '### ### ###',
    ], [
        'name' => 'Botswana',
        'flag' => '🇧🇼',
        'code' => 'BW',
        'dial_code' => '+267',
        'phone_mask' => '## ### ###',
    ], [
        'name' => 'Bouvet Island',
        'flag' => '🇧🇻',
        'code' => 'BV',
        'dial_code' => '+47',
        'phone_mask' => '',
    ], [
        'name' => 'Brazil',
        'flag' => '🇧🇷',
        'code' => 'BR',
        'dial_code' => '+55',
        'phone_mask' => '(##) #####-####',
    ], [
        'name' => 'British Indian Ocean Territory',
        'flag' => '🇮🇴',
        'code' => 'IO',
        'dial_code' => '+246',
        'phone_mask' => '### ####',
    ], [
        'name' => 'Brunei Darussalam',
        'flag' => '🇧🇳',
        'code' => 'BN',
        'dial_code' => '+673',
        'phone_mask' => '### ####',
    ], [
        'name' => 'Bulgaria',
        'flag' => '🇧🇬',
        'code' => 'BG',
        'dial_code' => '+359',
        'phone_mask' => '### ### ###',
    ], [
        'name' => 'Burkina Faso',
        'flag' => '🇧🇫',
        'code' => 'BF',
        'dial_code' => '+226',
        'phone_mask' => '## ## ## ##',
    ], [
        'name' => 'Burundi',
        'flag' => '🇧🇮',
        'code' => 'BI',
        'dial_code' => '+257',
        'phone_mask' => '## ## ## ##',
    ], [
        'name' => 'Cambodia',
        'flag' => '🇰🇭',
        'code' => 'KH',
        'dial_code' => '+855',
        'phone_mask' => '### ### ###',
    ], [
        'name' => 'Cameroon',
        'flag' => '🇨🇲',
        'code' => 'CM',
        'dial_code' => '+237',
        'phone_mask' => '# ## ## ## ##',
    ], [
        'name' => 'Canada',
        'flag' => '🇨🇦',
        'code' => 'CA',
        'dial_code' => '+1',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Cape Verde',
        'flag' => '🇨🇻',
        'code' => 'CV',
        'dial_code' => '+238',
        'phone_mask' => '### ## ##',
    ], [
        'name' => 'Cayman Islands',
        'flag' => '🇰🇾',
        'code' => 'KY',
        'dial_code' => '+345',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Central African Republic',
        'flag' => '🇨🇫',
        'code' => 'CF',
        'dial_code' => '+236',
        'phone_mask' => '## ## ## ##',
    ], [
        'name' => 'Chad',
        'flag' => '🇹🇩',
        'code' => 'TD',
        'dial_code' => '+235',
        'phone_mask' => '## ## ## ##',
    ], [
        'name' => 'Chile',
        'flag' => '🇨🇱',
        'code' => 'CL',
        'dial_code' => '+56',
        'phone_mask' => '(#) #### ####',
    ], [
        'name' => 'China',
        'flag' => '🇨🇳',
        'code' => 'CN',
        'dial_code' => '+86',
        'phone_mask' => '### #### ####',
    ], [
        'name' => 'Christmas Island',
        'flag' => '🇨🇽',
        'code' => 'CX',
        'dial_code' => '+61',
        'phone_mask' => '#### ### ###',
    ], [
        'name' => 'Cocos (Keeling) Islands',
        'flag' => '🇨🇨',
        'code' => 'CC',
        'dial_code' => '+61',
        'phone_mask' => '#### ### ###',
    ], [
        'name' => 'Colombia',
        'flag' => '🇨🇴',
        'code' => 'CO',
        'dial_code' => '+57',
        'phone_mask' => '### #######',
    ], [
        'name' => 'Comoros',
        'flag' => '🇰🇲',
        'code' => 'KM',
        'dial_code' => '+269',
        'phone_mask' => '### ## ##',
    ], [
        'name' => 'Congo',
        'flag' => '🇨🇬',
        'code' => 'CG',
        'dial_code' => '+242',
        'phone_mask' => '',
    ], [
        'name' => 'Congo, The Democratic Republic of the Congo',
        'flag' => '🇨🇩',
        'code' => 'CD',
        'dial_code' => '+243',
        'phone_mask' => '#### ### ###',
    ], [
        'name' => 'Cook Islands',
        'flag' => '🇨🇰',
        'code' => 'CK',
        'dial_code' => '+682',
        'phone_mask' => '## ###',
    ], [
        'name' => 'Costa Rica',
        'flag' => '🇨🇷',
        'code' => 'CR',
        'dial_code' => '+506',
        'phone_mask' => '#### ####',
    ], [
        'name' => "Cote d'Ivoire",
        'flag' => '🇨🇮',
        'code' => 'CI',
        'dial_code' => '+225',
        'phone_mask' => '',
    ], [
        'name' => 'Croatia',
        'flag' => '🇭🇷',
        'code' => 'HR',
        'dial_code' => '+385',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'Cuba',
        'flag' => '🇨🇺',
        'code' => 'CU',
        'dial_code' => '+53',
        'phone_mask' => '## #######',
    ], [
        'name' => 'Cyprus',
        'flag' => '🇨🇾',
        'code' => 'CY',
        'dial_code' => '+357',
        'phone_mask' => '## ######',
    ], [
        'name' => 'Czech Republic',
        'flag' => '🇨🇿',
        'code' => 'CZ',
        'dial_code' => '+420',
        'phone_mask' => '### ### ###',
    ], [
        'name' => 'Denmark',
        'flag' => '🇩🇰',
        'code' => 'DK',
        'dial_code' => '+45',
        'phone_mask' => '## ## ## ##',
    ], [
        'name' => 'Djibouti',
        'flag' => '🇩🇯',
        'code' => 'DJ',
        'dial_code' => '+253',
        'phone_mask' => '## ## ## ##',
    ], [
        'name' => 'Dominica',
        'flag' => '🇩🇲',
        'code' => 'DM',
        'dial_code' => '+1767',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Dominican Republic',
        'flag' => '🇩🇴',
        'code' => 'DO',
        'dial_code' => '+1849',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Ecuador',
        'flag' => '🇪🇨',
        'code' => 'EC',
        'dial_code' => '+593',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'Egypt',
        'flag' => '🇪🇬',
        'code' => 'EG',
        'dial_code' => '+20',
        'phone_mask' => '#### ### ####',
    ], [
        'name' => 'El Salvador',
        'flag' => '🇸🇻',
        'code' => 'SV',
        'dial_code' => '+503',
        'phone_mask' => '#### ####',
    ], [
        'name' => 'Equatorial Guinea',
        'flag' => '🇬🇶',
        'code' => 'GQ',
        'dial_code' => '+240',
        'phone_mask' => '### ### ###',
    ], [
        'name' => 'Eritrea',
        'flag' => '🇪🇷',
        'code' => 'ER',
        'dial_code' => '+291',
        'phone_mask' => '## ### ###',
    ], [
        'name' => 'Estonia',
        'flag' => '🇪🇪',
        'code' => 'EE',
        'dial_code' => '+372',
        'phone_mask' => '#### ####',
    ], [
        'name' => 'Ethiopia',
        'flag' => '🇪🇹',
        'code' => 'ET',
        'dial_code' => '+251',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'Falkland Islands (Malvinas)',
        'flag' => '🇫🇰',
        'code' => 'FK',
        'dial_code' => '+500',
        'phone_mask' => '#####',
    ], [
        'name' => 'Faroe Islands',
        'flag' => '🇫🇴',
        'code' => 'FO',
        'dial_code' => '+298',
        'phone_mask' => '######',
    ], [
        'name' => 'Fiji',
        'flag' => '🇫🇯',
        'code' => 'FJ',
        'dial_code' => '+679',
        'phone_mask' => '### ####',
    ], [
        'name' => 'Finland',
        'flag' => '🇫🇮',
        'code' => 'FI',
        'dial_code' => '+358',
        'phone_mask' => '### #######',
    ], [
        'name' => 'France',
        'flag' => '🇫🇷',
        'code' => 'FR',
        'dial_code' => '+33',
        'phone_mask' => '## ## ## ## ##',
    ], [
        'name' => 'French Guiana',
        'flag' => '🇬🇫',
        'code' => 'GF',
        'dial_code' => '+594',
        'phone_mask' => '#### ## ## ##',
    ], [
        'name' => 'French Polynesia',
        'flag' => '🇵🇫',
        'code' => 'PF',
        'dial_code' => '+689',
        'phone_mask' => '## ## ## ##',
    ], [
        'name' => 'French Southern Territories',
        'flag' => '🇹🇫',
        'code' => 'TF',
        'dial_code' => '+262',
        'phone_mask' => '',
    ], [
        'name' => 'Gabon',
        'flag' => '🇬🇦',
        'code' => 'GA',
        'dial_code' => '+241',
        'phone_mask' => '## ## ## ##',
    ], [
        'name' => 'Gambia',
        'flag' => '🇬🇲',
        'code' => 'GM',
        'dial_code' => '+220',
        'phone_mask' => '### ####',
    ], [
        'name' => 'Georgia',
        'flag' => '🇬🇪',
        'code' => 'GE',
        'dial_code' => '+995',
        'phone_mask' => '### ## ## ##',
    ], [
        'name' => 'Germany',
        'flag' => '🇩🇪',
        'code' => 'DE',
        'dial_code' => '+49',
        'phone_mask' => '##### #######',
    ], [
        'name' => 'Ghana',
        'flag' => '🇬🇭',
        'code' => 'GH',
        'dial_code' => '+233',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'Gibraltar',
        'flag' => '🇬🇮',
        'code' => 'GI',
        'dial_code' => '+350',
        'phone_mask' => '########',
    ], [
        'name' => 'Greece',
        'flag' => '🇬🇷',
        'code' => 'GR',
        'dial_code' => '+30',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'Greenland',
        'flag' => '🇬🇱',
        'code' => 'GL',
        'dial_code' => '+299',
        'phone_mask' => '## ## ##',
    ], [
        'name' => 'Grenada',
        'flag' => '🇬🇩',
        'code' => 'GD',
        'dial_code' => '+1473',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Guadeloupe',
        'flag' => '🇬🇵',
        'code' => 'GP',
        'dial_code' => '+590',
        'phone_mask' => '#### ## ## ##',
    ], [
        'name' => 'Guam',
        'flag' => '🇬🇺',
        'code' => 'GU',
        'dial_code' => '+1671',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Guatemala',
        'flag' => '🇬🇹',
        'code' => 'GT',
        'dial_code' => '+502',
        'phone_mask' => '#### ####',
    ], [
        'name' => 'Guernsey',
        'flag' => '🇬🇬',
        'code' => 'GG',
        'dial_code' => '+44',
        'phone_mask' => '##### ######',
    ], [
        'name' => 'Guinea',
        'flag' => '🇬🇳',
        'code' => 'GN',
        'dial_code' => '+224',
        'phone_mask' => '### ## ## ##',
    ], [
        'name' => 'Guinea-Bissau',
        'flag' => '🇬🇼',
        'code' => 'GW',
        'dial_code' => '+245',
        'phone_mask' => '### ### ###',
    ], [
        'name' => 'Guyana',
        'flag' => '🇬🇾',
        'code' => 'GY',
        'dial_code' => '+592',
        'phone_mask' => '### ####',
    ], [
        'name' => 'Haiti',
        'flag' => '🇭🇹',
        'code' => 'HT',
        'dial_code' => '+509',
        'phone_mask' => '## ## ####',
    ], [
        'name' => 'Heard Island and Mcdonald Islands',
        'flag' => '🇭🇲',
        'code' => 'HM',
        'dial_code' => '+672',
        'phone_mask' => '',
    ], [
        'name' => 'Holy See (Vatican City State)',
        'flag' => '🇻🇦',
        'code' => 'VA',
        'dial_code' => '+379',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'Honduras',
        'flag' => '🇭🇳',
        'code' => 'HN',
        'dial_code' => '+504',
        'phone_mask' => '####-####',
    ], [
        'name' => 'Hong Kong',
        'flag' => '🇭🇰',
        'code' => 'HK',
        'dial_code' => '+852',
        'phone_mask' => '#### ####',
    ], [
        'name' => 'Hungary',
        'flag' => '🇭🇺',
        'code' => 'HU',
        'dial_code' => '+36',
        'phone_mask' => '## ## ### ####',
    ], [
        'name' => 'Iceland',
        'flag' => '🇮🇸',
        'code' => 'IS',
        'dial_code' => '+354',
        'phone_mask' => '### ####',
    ], [
        'name' => 'India',
        'flag' => '🇮🇳',
        'code' => 'IN',
        'dial_code' => '+91',
        'phone_mask' => '###### #####',
    ], [
        'name' => 'Indonesia',
        'flag' => '🇮🇩',
        'code' => 'ID',
        'dial_code' => '+62',
        'phone_mask' => '####-###-###',
    ], [
        'name' => 'Iran, Islamic Republic of Persian Gulf',
        'flag' => '🇮🇷',
        'code' => 'IR',
        'dial_code' => '+98',
        'phone_mask' => '#### ### ####',
    ], [
        'name' => 'Iraq',
        'flag' => '🇮🇶',
        'code' => 'IQ',
        'dial_code' => '+964',
        'phone_mask' => '#### ### ####',
    ], [
        'name' => 'Ireland',
        'flag' => '🇮🇪',
        'code' => 'IE',
        'dial_code' => '+353',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'Isle of Man',
        'flag' => '🇮🇲',
        'code' => 'IM',
        'dial_code' => '+44',
        'phone_mask' => '##### ######',
    ], [
        'name' => 'Israel',
        'flag' => '🇮🇱',
        'code' => 'IL',
        'dial_code' => '+972',
        'phone_mask' => '###-###-####',
    ], [
        'name' => 'Italy',
        'flag' => '🇮🇹',
        'code' => 'IT',
        'dial_code' => '+39',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'Jamaica',
        'flag' => '🇯🇲',
        'code' => 'JM',
        'dial_code' => '+1876',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Japan',
        'flag' => '🇯🇵',
        'code' => 'JP',
        'dial_code' => '+81',
        'phone_mask' => '###-####-####',
    ], [
        'name' => 'Jersey',
        'flag' => '🇯🇪',
        'code' => 'JE',
        'dial_code' => '+44',
        'phone_mask' => '##### ######',
    ], [
        'name' => 'Jordan',
        'flag' => '🇯🇴',
        'code' => 'JO',
        'dial_code' => '+962',
        'phone_mask' => '## #### ####',
    ], [
        'name' => 'Kazakhstan',
        'flag' => '🇰🇿',
        'code' => 'KZ',
        'dial_code' => '+7',
        'phone_mask' => '# (###) ### ####',
    ], [
        'name' => 'Kenya',
        'flag' => '🇰🇪',
        'code' => 'KE',
        'dial_code' => '+254',
        'phone_mask' => '#### ######',
    ], [
        'name' => 'Kiribati',
        'flag' => '🇰🇮',
        'code' => 'KI',
        'dial_code' => '+686',
        'phone_mask' => '########',
    ], [
        'name' => "Korea, Democratic People's Republic of Korea",
        'flag' => '🇰🇵',
        'code' => 'KP',
        'dial_code' => '+850',
        'phone_mask' => '#### ### ####',
    ], [
        'name' => 'Korea, Republic of South Korea',
        'flag' => '🇰🇷',
        'code' => 'KR',
        'dial_code' => '+82',
        'phone_mask' => '###-####-####',
    ], [
        'name' => 'Kosovo',
        'flag' => '🇽🇰',
        'code' => 'XK',
        'dial_code' => '+383',
        'phone_mask' => '',
    ], [
        'name' => 'Kuwait',
        'flag' => '🇰🇼',
        'code' => 'KW',
        'dial_code' => '+965',
        'phone_mask' => '### #####',
    ], [
        'name' => 'Kyrgyzstan',
        'flag' => '🇰🇬',
        'code' => 'KG',
        'dial_code' => '+996',
        'phone_mask' => '#### ### ###',
    ], [
        'name' => 'Laos',
        'flag' => '🇱🇦',
        'code' => 'LA',
        'dial_code' => '+856',
        'phone_mask' => '### ## ### ###',
    ], [
        'name' => 'Latvia',
        'flag' => '🇱🇻',
        'code' => 'LV',
        'dial_code' => '+371',
        'phone_mask' => '## ### ###',
    ], [
        'name' => 'Lebanon',
        'flag' => '🇱🇧',
        'code' => 'LB',
        'dial_code' => '+961',
        'phone_mask' => '## ### ###',
    ], [
        'name' => 'Lesotho',
        'flag' => '🇱🇸',
        'code' => 'LS',
        'dial_code' => '+266',
        'phone_mask' => '#### ####',
    ], [
        'name' => 'Liberia',
        'flag' => '🇱🇷',
        'code' => 'LR',
        'dial_code' => '+231',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'Libyan Arab Jamahiriya',
        'flag' => '🇱🇾',
        'code' => 'LY',
        'dial_code' => '+218',
        'phone_mask' => '###-#######',
    ], [
        'name' => 'Liechtenstein',
        'flag' => '🇱🇮',
        'code' => 'LI',
        'dial_code' => '+423',
        'phone_mask' => '### ### ###',
    ], [
        'name' => 'Lithuania',
        'flag' => '🇱🇹',
        'code' => 'LT',
        'dial_code' => '+370',
        'phone_mask' => '(#-###) #####',
    ], [
        'name' => 'Luxembourg',
        'flag' => '🇱🇺',
        'code' => 'LU',
        'dial_code' => '+352',
        'phone_mask' => '### ### ###',
    ], [
        'name' => 'Macao',
        'flag' => '🇲🇴',
        'code' => 'MO',
        'dial_code' => '+853',
        'phone_mask' => '#### ####',
    ], [
        'name' => 'Macedonia',
        'flag' => '🇲🇰',
        'code' => 'MK',
        'dial_code' => '+389',
        'phone_mask' => '### ### ###',
    ], [
        'name' => 'Madagascar',
        'flag' => '🇲🇬',
        'code' => 'MG',
        'dial_code' => '+261',
        'phone_mask' => '### ## ### ##',
    ], [
        'name' => 'Malawi',
        'flag' => '🇲🇼',
        'code' => 'MW',
        'dial_code' => '+265',
        'phone_mask' => '#### ## ## ##',
    ], [
        'name' => 'Malaysia',
        'flag' => '🇲🇾',
        'code' => 'MY',
        'dial_code' => '+60',
        'phone_mask' => '###-### ####',
    ], [
        'name' => 'Maldives',
        'flag' => '🇲🇻',
        'code' => 'MV',
        'dial_code' => '+960',
        'phone_mask' => '###-####',
    ], [
        'name' => 'Mali',
        'flag' => '🇲🇱',
        'code' => 'ML',
        'dial_code' => '+223',
        'phone_mask' => '## ## ## ##',
    ], [
        'name' => 'Malta',
        'flag' => '🇲🇹',
        'code' => 'MT',
        'dial_code' => '+356',
        'phone_mask' => '#### ####',
    ], [
        'name' => 'Marshall Islands',
        'flag' => '🇲🇭',
        'code' => 'MH',
        'dial_code' => '+692',
        'phone_mask' => '###-####',
    ], [
        'name' => 'Martinique',
        'flag' => '🇲🇶',
        'code' => 'MQ',
        'dial_code' => '+596',
        'phone_mask' => '#### ## ## ##',
    ], [
        'name' => 'Mauritania',
        'flag' => '🇲🇷',
        'code' => 'MR',
        'dial_code' => '+222',
        'phone_mask' => '## ## ## ##',
    ], [
        'name' => 'Mauritius',
        'flag' => '🇲🇺',
        'code' => 'MU',
        'dial_code' => '+230',
        'phone_mask' => '#### ####',
    ], [
        'name' => 'Mayotte',
        'flag' => '🇾🇹',
        'code' => 'YT',
        'dial_code' => '+262',
        'phone_mask' => '#### ## ## ##',
    ], [
        'name' => 'Mexico',
        'flag' => '🇲🇽',
        'code' => 'MX',
        'dial_code' => '+52',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'Micronesia, Federated States of Micronesia',
        'flag' => '🇫🇲',
        'code' => 'FM',
        'dial_code' => '+691',
        'phone_mask' => '### ####',
    ], [
        'name' => 'Moldova',
        'flag' => '🇲🇩',
        'code' => 'MD',
        'dial_code' => '+373',
        'phone_mask' => '#### ## ###',
    ], [
        'name' => 'Monaco',
        'flag' => '🇲🇨',
        'code' => 'MC',
        'dial_code' => '+377',
        'phone_mask' => '## ## ## ## ##',
    ], [
        'name' => 'Mongolia',
        'flag' => '🇲🇳',
        'code' => 'MN',
        'dial_code' => '+976',
        'phone_mask' => '#### ####',
    ], [
        'name' => 'Montenegro',
        'flag' => '🇲🇪',
        'code' => 'ME',
        'dial_code' => '+382',
        'phone_mask' => '### ### ###',
    ], [
        'name' => 'Montserrat',
        'flag' => '🇲🇸',
        'code' => 'MS',
        'dial_code' => '+1664',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Morocco',
        'flag' => '🇲🇦',
        'code' => 'MA',
        'dial_code' => '+212',
        'phone_mask' => '####-######',
    ], [
        'name' => 'Mozambique',
        'flag' => '🇲🇿',
        'code' => 'MZ',
        'dial_code' => '+258',
        'phone_mask' => '## ### ####',
    ], [
        'name' => 'Myanmar',
        'flag' => '🇲🇲',
        'code' => 'MM',
        'dial_code' => '+95',
        'phone_mask' => '## ### ####',
    ], [
        'name' => 'Namibia',
        'flag' => '🇳🇦',
        'code' => 'NA',
        'dial_code' => '+264',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'Nauru',
        'flag' => '🇳🇷',
        'code' => 'NR',
        'dial_code' => '+674',
        'phone_mask' => '### ####',
    ], [
        'name' => 'Nepal',
        'flag' => '🇳🇵',
        'code' => 'NP',
        'dial_code' => '+977',
        'phone_mask' => '###-#######',
    ], [
        'name' => 'Netherlands',
        'flag' => '🇳🇱',
        'code' => 'NL',
        'dial_code' => '+31',
        'phone_mask' => '## ########',
    ], [
        'name' => 'Netherlands Antilles',
        'flag' => '',
        'code' => 'AN',
        'dial_code' => '+599',
        'phone_mask' => '',
    ], [
        'name' => 'New Caledonia',
        'flag' => '🇳🇨',
        'code' => 'NC',
        'dial_code' => '+687',
        'phone_mask' => '##.##.##',
    ], [
        'name' => 'New Zealand',
        'flag' => '🇳🇿',
        'code' => 'NZ',
        'dial_code' => '+64',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'Nicaragua',
        'flag' => '🇳🇮',
        'code' => 'NI',
        'dial_code' => '+505',
        'phone_mask' => '#### ####',
    ], [
        'name' => 'Niger',
        'flag' => '🇳🇪',
        'code' => 'NE',
        'dial_code' => '+227',
        'phone_mask' => '## ## ## ##',
    ], [
        'name' => 'Nigeria',
        'flag' => '🇳🇬',
        'code' => 'NG',
        'dial_code' => '+234',
        'phone_mask' => '#### ### ####',
    ], [
        'name' => 'Niue',
        'flag' => '🇳🇺',
        'code' => 'NU',
        'dial_code' => '+683',
        'phone_mask' => '### ####',
    ], [
        'name' => 'Norfolk Island',
        'flag' => '🇳🇫',
        'code' => 'NF',
        'dial_code' => '+672',
        'phone_mask' => '# #####',
    ], [
        'name' => 'Northern Mariana Islands',
        'flag' => '🇲🇵',
        'code' => 'MP',
        'dial_code' => '+1670',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Norway',
        'flag' => '🇳🇴',
        'code' => 'NO',
        'dial_code' => '+47',
        'phone_mask' => '### ## ###',
    ], [
        'name' => 'Oman',
        'flag' => '🇴🇲',
        'code' => 'OM',
        'dial_code' => '+968',
        'phone_mask' => '#### ####',
    ], [
        'name' => 'Pakistan',
        'flag' => '🇵🇰',
        'code' => 'PK',
        'dial_code' => '+92',
        'phone_mask' => '#### #######',
    ], [
        'name' => 'Palau',
        'flag' => '🇵🇼',
        'code' => 'PW',
        'dial_code' => '+680',
        'phone_mask' => '### ####',
    ], [
        'name' => 'Palestinian Territory, Occupied',
        'flag' => '🇵🇸',
        'code' => 'PS',
        'dial_code' => '+970',
        'phone_mask' => '#### ### ###',
    ], [
        'name' => 'Panama',
        'flag' => '🇵🇦',
        'code' => 'PA',
        'dial_code' => '+507',
        'phone_mask' => '####-####',
    ], [
        'name' => 'Papua New Guinea',
        'flag' => '🇵🇬',
        'code' => 'PG',
        'dial_code' => '+675',
        'phone_mask' => '#### ####',
    ], [
        'name' => 'Paraguay',
        'flag' => '🇵🇾',
        'code' => 'PY',
        'dial_code' => '+595',
        'phone_mask' => '#### ######',
    ], [
        'name' => 'Peru',
        'flag' => '🇵🇪',
        'code' => 'PE',
        'dial_code' => '+51',
        'phone_mask' => '### ### ###',
    ], [
        'name' => 'Philippines',
        'flag' => '🇵🇭',
        'code' => 'PH',
        'dial_code' => '+63',
        'phone_mask' => '#### ### ####',
    ], [
        'name' => 'Pitcairn',
        'flag' => '🇵🇳',
        'code' => 'PN',
        'dial_code' => '+64',
        'phone_mask' => '',
    ], [
        'name' => 'Poland',
        'flag' => '🇵🇱',
        'code' => 'PL',
        'dial_code' => '+48',
        'phone_mask' => '### ### ###',
    ], [
        'name' => 'Portugal',
        'flag' => '🇵🇹',
        'code' => 'PT',
        'dial_code' => '+351',
        'phone_mask' => '### ### ###',
    ], [
        'name' => 'Puerto Rico',
        'flag' => '🇵🇷',
        'code' => 'PR',
        'dial_code' => '+1939',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Qatar',
        'flag' => '🇶🇦',
        'code' => 'QA',
        'dial_code' => '+974',
        'phone_mask' => '#### ####',
    ], [
        'name' => 'Romania',
        'flag' => '🇷🇴',
        'code' => 'RO',
        'dial_code' => '+40',
        'phone_mask' => '#### ### ###',
    ], [
        'name' => 'Russia',
        'flag' => '🇷🇺',
        'code' => 'RU',
        'dial_code' => '+7',
        'phone_mask' => '# (###) ###-##-##',
    ], [
        'name' => 'Rwanda',
        'flag' => '🇷🇼',
        'code' => 'RW',
        'dial_code' => '+250',
        'phone_mask' => '#### ### ###',
    ], [
        'name' => 'Reunion',
        'flag' => '🇷🇪',
        'code' => 'RE',
        'dial_code' => '+262',
        'phone_mask' => '#### ## ## ##',
    ], [
        'name' => 'Saint Barthelemy',
        'flag' => '🇧🇱',
        'code' => 'BL',
        'dial_code' => '+590',
        'phone_mask' => '#### ## ## ##',
    ], [
        'name' => 'Saint Helena, Ascension and Tristan Da Cunha',
        'flag' => '🇸🇭',
        'code' => 'SH',
        'dial_code' => '+290',
        'phone_mask' => '#####',
    ], [
        'name' => 'Saint Kitts and Nevis',
        'flag' => '🇰🇳',
        'code' => 'KN',
        'dial_code' => '+1869',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Saint Lucia',
        'flag' => '🇱🇨',
        'code' => 'LC',
        'dial_code' => '+1758',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Saint Martin',
        'flag' => '🇲🇫',
        'code' => 'MF',
        'dial_code' => '+590',
        'phone_mask' => '#### ## ## ##',
    ], [
        'name' => 'Saint Pierre and Miquelon',
        'flag' => '🇵🇲',
        'code' => 'PM',
        'dial_code' => '+508',
        'phone_mask' => '### ## ##',
    ], [
        'name' => 'Saint Vincent and the Grenadines',
        'flag' => '🇻🇨',
        'code' => 'VC',
        'dial_code' => '+1784',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Samoa',
        'flag' => '🇼🇸',
        'code' => 'WS',
        'dial_code' => '+685',
        'phone_mask' => '## #####',
    ], [
        'name' => 'San Marino',
        'flag' => '🇸🇲',
        'code' => 'SM',
        'dial_code' => '+378',
        'phone_mask' => '## ## ## ##',
    ], [
        'name' => 'Sao Tome and Principe',
        'flag' => '🇸🇹',
        'code' => 'ST',
        'dial_code' => '+239',
        'phone_mask' => '### ####',
    ], [
        'name' => 'Saudi Arabia',
        'flag' => '🇸🇦',
        'code' => 'SA',
        'dial_code' => '+966',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'Senegal',
        'flag' => '🇸🇳',
        'code' => 'SN',
        'dial_code' => '+221',
        'phone_mask' => '## ### ## ##',
    ], [
        'name' => 'Serbia',
        'flag' => '🇷🇸',
        'code' => 'RS',
        'dial_code' => '+381',
        'phone_mask' => '### #######',
    ], [
        'name' => 'Seychelles',
        'flag' => '🇸🇨',
        'code' => 'SC',
        'dial_code' => '+248',
        'phone_mask' => '# ### ###',
    ], [
        'name' => 'Sierra Leone',
        'flag' => '🇸🇱',
        'code' => 'SL',
        'dial_code' => '+232',
        'phone_mask' => '(###) ######',
    ], [
        'name' => 'Singapore',
        'flag' => '🇸🇬',
        'code' => 'SG',
        'dial_code' => '+65',
        'phone_mask' => '#### ####',
    ], [
        'name' => 'Slovakia',
        'flag' => '🇸🇰',
        'code' => 'SK',
        'dial_code' => '+421',
        'phone_mask' => '#### ### ###',
    ], [
        'name' => 'Slovenia',
        'flag' => '🇸🇮',
        'code' => 'SI',
        'dial_code' => '+386',
        'phone_mask' => '### ### ###',
    ], [
        'name' => 'Solomon Islands',
        'flag' => '🇸🇧',
        'code' => 'SB',
        'dial_code' => '+677',
        'phone_mask' => '## #####',
    ], [
        'name' => 'Somalia',
        'flag' => '🇸🇴',
        'code' => 'SO',
        'dial_code' => '+252',
        'phone_mask' => '# #######',
    ], [
        'name' => 'South Africa',
        'flag' => '🇿🇦',
        'code' => 'ZA',
        'dial_code' => '+27',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'South Sudan',
        'flag' => '🇸🇸',
        'code' => 'SS',
        'dial_code' => '+211',
        'phone_mask' => '#### ### ###',
    ], [
        'name' => 'South Georgia and the South Sandwich Islands',
        'flag' => '🇬🇸',
        'code' => 'GS',
        'dial_code' => '+500',
        'phone_mask' => '',
    ], [
        'name' => 'Spain',
        'flag' => '🇪🇸',
        'code' => 'ES',
        'dial_code' => '+34',
        'phone_mask' => '### ## ## ##',
    ], [
        'name' => 'Sri Lanka',
        'flag' => '🇱🇰',
        'code' => 'LK',
        'dial_code' => '+94',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'Sudan',
        'flag' => '🇸🇩',
        'code' => 'SD',
        'dial_code' => '+249',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'Suriname',
        'flag' => '🇸🇷',
        'code' => 'SR',
        'dial_code' => '+597',
        'phone_mask' => '###-####',
    ], [
        'name' => 'Svalbard and Jan Mayen',
        'flag' => '🇸🇯',
        'code' => 'SJ',
        'dial_code' => '+47',
        'phone_mask' => '### ## ###',
    ], [
        'name' => 'Swaziland',
        'flag' => '🇸🇿',
        'code' => 'SZ',
        'dial_code' => '+268',
        'phone_mask' => '#### ####',
    ], [
        'name' => 'Sweden',
        'flag' => '🇸🇪',
        'code' => 'SE',
        'dial_code' => '+46',
        'phone_mask' => '###-### ## ##',
    ], [
        'name' => 'Switzerland',
        'flag' => '🇨🇭',
        'code' => 'CH',
        'dial_code' => '+41',
        'phone_mask' => '### ### ## ##',
    ], [
        'name' => 'Syrian Arab Republic',
        'flag' => '🇸🇾',
        'code' => 'SY',
        'dial_code' => '+963',
        'phone_mask' => '#### ### ###',
    ], [
        'name' => 'Taiwan',
        'flag' => '🇹🇼',
        'code' => 'TW',
        'dial_code' => '+886',
        'phone_mask' => '#### ### ###',
    ], [
        'name' => 'Tajikistan',
        'flag' => '🇹🇯',
        'code' => 'TJ',
        'dial_code' => '+992',
        'phone_mask' => '### ## ####',
    ], [
        'name' => 'Tanzania, United Republic of Tanzania',
        'flag' => '🇹🇿',
        'code' => 'TZ',
        'dial_code' => '+255',
        'phone_mask' => '#### ### ###',
    ], [
        'name' => 'Thailand',
        'flag' => '🇹🇭',
        'code' => 'TH',
        'dial_code' => '+66',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'Timor-Leste',
        'flag' => '🇹🇱',
        'code' => 'TL',
        'dial_code' => '+670',
        'phone_mask' => '#### ####',
    ], [
        'name' => 'Togo',
        'flag' => '🇹🇬',
        'code' => 'TG',
        'dial_code' => '+228',
        'phone_mask' => '## ## ## ##',
    ], [
        'name' => 'Tokelau',
        'flag' => '🇹🇰',
        'code' => 'TK',
        'dial_code' => '+690',
        'phone_mask' => '####',
    ], [
        'name' => 'Tonga',
        'flag' => '🇹🇴',
        'code' => 'TO',
        'dial_code' => '+676',
        'phone_mask' => '### ####',
    ], [
        'name' => 'Trinidad and Tobago',
        'flag' => '🇹🇹',
        'code' => 'TT',
        'dial_code' => '+1868',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Tunisia',
        'flag' => '🇹🇳',
        'code' => 'TN',
        'dial_code' => '+216',
        'phone_mask' => '## ### ###',
    ], [
        'name' => 'Turkey',
        'flag' => '🇹🇷',
        'code' => 'TR',
        'dial_code' => '+90',
        'phone_mask' => '#### ### ## ##',
    ], [
        'name' => 'Turkmenistan',
        'flag' => '🇹🇲',
        'code' => 'TM',
        'dial_code' => '+993',
        'phone_mask' => '# ## ######',
    ], [
        'name' => 'Turks and Caicos Islands',
        'flag' => '🇹🇨',
        'code' => 'TC',
        'dial_code' => '+1649',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Tuvalu',
        'flag' => '🇹🇻',
        'code' => 'TV',
        'dial_code' => '+688',
        'phone_mask' => '## ####',
    ], [
        'name' => 'Uganda',
        'flag' => '🇺🇬',
        'code' => 'UG',
        'dial_code' => '+256',
        'phone_mask' => '#### ######',
    ], [
        'name' => 'Ukraine',
        'flag' => '🇺🇦',
        'code' => 'UA',
        'dial_code' => '+380',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'United Arab Emirates',
        'flag' => '🇦🇪',
        'code' => 'AE',
        'dial_code' => '+971',
        'phone_mask' => '### ### ####',
    ], [
        'name' => 'United Kingdom',
        'flag' => '🇬🇧',
        'code' => 'GB',
        'dial_code' => '+44',
        'phone_mask' => '### #### ####',
    ], [
        'name' => 'United States',
        'flag' => '🇺🇸',
        'code' => 'US',
        'dial_code' => '+1',
        'phone_mask' => '###-###-####',
    ], [
        'name' => 'Uruguay',
        'flag' => '🇺🇾',
        'code' => 'UY',
        'dial_code' => '+598',
        'phone_mask' => '### ### ###',
    ], [
        'name' => 'Uzbekistan',
        'flag' => '🇺🇿',
        'code' => 'UZ',
        'dial_code' => '+998',
        'phone_mask' => '# ## ### ## ##',
    ], [
        'name' => 'Vanuatu',
        'flag' => '🇻🇺',
        'code' => 'VU',
        'dial_code' => '+678',
        'phone_mask' => '### ####',
    ], [
        'name' => 'Venezuela, Bolivarian Republic of Venezuela',
        'flag' => '🇻🇪',
        'code' => 'VE',
        'dial_code' => '+58',
        'phone_mask' => '####-#######',
    ], [
        'name' => 'Vietnam',
        'flag' => '🇻🇳',
        'code' => 'VN',
        'dial_code' => '+84',
        'phone_mask' => '### ### ## ##',
    ], [
        'name' => 'Virgin Islands, British',
        'flag' => '🇻🇬',
        'code' => 'VG',
        'dial_code' => '+1284',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Virgin Islands, U.S.',
        'flag' => '🇻🇮',
        'code' => 'VI',
        'dial_code' => '+1340',
        'phone_mask' => '(###) ###-####',
    ], [
        'name' => 'Wallis and Futuna',
        'flag' => '🇼🇫',
        'code' => 'WF',
        'dial_code' => '+681',
        'phone_mask' => '## ## ##',
    ], [
        'name' => 'Yemen',
        'flag' => '🇾🇪',
        'code' => 'YE',
        'dial_code' => '+967',
        'phone_mask' => '#### ### ###',
    ], [
        'name' => 'Zambia',
        'flag' => '🇿🇲',
        'code' => 'ZM',
        'dial_code' => '+260',
        'phone_mask' => '### #######',
    ], [
        'name' => 'Zimbabwe',
        'flag' => '🇿🇼',
        'code' => 'ZW',
        'dial_code' => '+263',
        'phone_mask' => '### ### ####',
    ]
];
